example/cities/urls.py
from django.conf.urls import url
from cities.views import CityCreateView, CityListView, CityDetailView

urlpatterns = [
    url(r'^$', CityListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', CityDetailView.as_view(), name="detail"),
    url(r'^create/$', CityCreateView.as_view(), name="create"),
]

example/example/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('cities:list'))),
    url(r'^admin/', admin.site.urls),
    url(r'^cities/', include('cities.urls', namespace='cities')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

example/cities/models.py
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point

POINT = Point(-104.9903, 39.7392, srid=4326)


class City(models.Model):
    name = models.CharField(max_length=255)
    coordinates = models.PointField(help_text="To generate the map for your location")
    city_hall = models.PointField(blank=True, null=True)

    def __unicode__(self):
        return self.name


class District(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=255)
    location = models.PointField(help_text="To generate the map for your location")

    def __unicode__(self):
        return self.name

example/cities/forms.py
from django import forms

from cities.models import City
from mapwidgets.widgets import GooglePointFieldWidget, GoogleStaticMapWidget, GoogleStaticOverlayMapWidget


class CityCreateForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GooglePointFieldWidget,
            'city_hall': GooglePointFieldWidget,
        }


class CityDetailForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ("name", "coordinates", "city_hall")
        widgets = {
            'coordinates': GoogleStaticMapWidget(zoom=12, size="240x240"),
            'city_hall': GoogleStaticOverlayMapWidget(zoom=12, thumbnail_size="50x50", size="640x640"),
        }

example/cities/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import FormView, ListView, UpdateView

from cities.forms import CityCreateForm, CityDetailForm
from cities.models import City


class CityListView(ListView):
    queryset = City.objects.all()
    template_name = "cities/list.html"
    context_object_name = "cities"


class CityDetailView(UpdateView):
    form_class = CityDetailForm
    model = City
    template_name = "cities/detail.html"


class CityCreateView(FormView):
    template_name = "cities/form.html"
    form_class = CityCreateForm
    success_url = reverse_lazy("cities:list")

    def form_valid(self, form):
        form.save()
        return super(CityCreateView, self).form_valid(form)

example/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    <title>Map Widgets - Example Project</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>



    {% block extrahead %}
    {% endblock extrahead %}

</head>
<body>
    <div class="container help-block" >
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

example/templates/cities/detail.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}
{% endblock extrahead %}

{% block content %}
    {{ form.as_p }}
{% endblock content %}

example/templates/cities/form.html
{% extends "base.html" %}

{% block extrahead %}
    {{ form.media }}

    <script type="text/javascript">
        $(document).on("google_point_map_widget:marker_create", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng); // created marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        });

        $(document).on("google_point_map_widget:marker_change", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng);  // changed marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        });

        $(document).on("google_point_map_widget:marker_delete", function (e, lat, lng, locationInputElem, mapWrapID) {
            console.log(locationInputElem); // django widget textarea widget (hidden)
            console.log(lat, lng);  // deleted marker coordinates
            console.log(mapWrapID); // map widget wrapper element ID
        })
    </script>
{% endblock extrahead %}

{% block content %}
    <form action="{% url "cities:create" %}" method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock content %}

example/templates/cities/list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 20px"><a href="{% url "cities:create" %}" class="btn btn-default block">Create</a></div>
        <ul class="block">
            {% for city in cities %}
                <li><a href="{% url "cities:detail" city.id %}">{{ city.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}